# Generated by Django 5.2 on 2025-10-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_customer_mobile_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
